### ISSUE TITLE
How to disable response validation?

### ISSUE THREAD

**Issue by keepitsimple** [jayalfredprufrock/nestjs-typebox#44]
Hello,

Right now response is mandatory parameter for validation. My attempts to remove it or suppress it doesn't work.

Any suggestions will be highly appreciated!

Thank you

**Comment by keepitsimple** [comment]
Yes, I use version "nestjs-typebox": "2.6.1"

But any my attempt to omit it failed. Validator shows error in this case. :(

**Comment by smiley-uriux** [comment]
Interesting, so it sounds like you mean a runtime error, not a type error?

I'll take a closer look at this, but again I'm using this package in several projects in production so I'm fairly certain things are working under normal circumstances. Perhaps one thing you can try in the meantime is to use `Type.Any()` for the response schema. It could also be that the version of type box you are on is incompatible. There have been a lot of changes in the library over the past month or two and so this project has been pinning the type box version until things stabilize. You can expect an update to the latest version sometime this month.

**Comment by keepitsimple** [comment]
Thank you! 

The working solution for 2.6.1 is
```
 response: { schema: Type.Any(), stripUnknownProps: false }
 ```
