### ISSUE TITLE
Documentation conveys incorrect usage

### ISSUE THREAD

**Issue by eropple** [jayalfredprufrock/nestjs-typebox#49]
```
@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @HttpEndpoint({
    method: 'GET',
    path: '/ping/:name',
    description: 'Returns a greeting',
    summary: 'Greeting',
    tags: ['meta'],
    request: [
      { name: 'name', type: 'param', schema: Type.String() },
    ],
    responses: {
      200: { description: 'OK', content: PingDto },
    }
  })
  ping(name: string): PingDto {
    return { pong: `Hello, ${name}!` }
  }
}
```

leads to

```
Object literal may only specify known properties, and 'request' does not exist in type 'HttpEndpointDecoratorConfig<TSchema, Omit<ResponseValidatorConfig<TSchema>, "responseCode">, RequestValidatorConfig[]>'.ts(2353)
```

The most-correct way I can puzzle out is more like this:

```
@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @HttpEndpoint({
    method: 'GET',
    path: '/ping/:name',
    description: 'Returns a greeting',
    summary: 'Greeting',
    tags: ['meta'],
    responseCode: 200,
    validate: {
      request: [
        { name: 'name', type: 'param', schema: Type.String() },
      ],
      response: PingDto,
    },
  })
  ping(name: string): PingDto {
    return { pong: `Hello, ${name}!` }
  }
}
```

Thanks for taking a look!

**Comment by jayalfredprufrock** [comment]
You are absolutely right, the docs conflate the two different decorator's syntax. The `@Validate()` decorator accepts a request array and response schema (I have plans to accept an object/array of response schemas to represent different responses per http status code for v3). The `HttpEndpoint()` decorator accepts a "validate" prop that is essentially a pass through to the @Validate() decorator. I'll push a fix to the docs shortly.

**Comment by eropple** [comment]
Right on, thanks! Really liking the library so far - I made a Nest
validation library once upon a time (
https://github.com/eropple/nestjs-openapi3 ) but didn’t keep it updated,
and in moving back from Fastify yours has been really ergonomic to use.
