### ISSUE TITLE
Support validation with AJV instead of `TypeBox.Compile`

### ISSUE THREAD

**Issue by MatanYadaev** [jayalfredprufrock/nestjs-typebox#55]

**Comment by MatanYadaev** [comment]
@jayalfredprufrock Can you please explain which developments you have been watching and waiting to stabilize in TypeBox?

**Comment by jayalfredprufrock** [comment]
I'm going to close this out for now. With the v3 release, I've converged on an approach to defaults/transforms/sanitizing using standard typebox utilities. At this point I don't see introducing official AJV support anytime soon. With some of the recent typebox developments, I'm happy with the current state of things and don't really miss any features from AJV.
