### ISSUE TITLE
OpenAPI: Response description

### ISSUE THREAD

**Issue by anotheri** [jayalfredprufrock/nestjs-typebox#63]
Based on this code: https://github.com/jayalfredprufrock/nestjs-typebox/blob/main/src/decorators.ts#L121 it seems it's impossible to define `description` and `example` for `ApiOkResponse`, it would be nice to have though. 

Also it's not so clear how to mange schemas/description for other response statuses (e.g. to have the same openAPI result as with using both `@ApiOkResponse` and `@ApiBadRequestResponse` decorators)? Is that possible via `@Validate` or `@ HttpEndpoint` decorators now? If so, could you provide an example please?

The only approach i've figured out is to define `@ApiBadRequestResponse` after `@Validate`, i.e.:
```
@ApiBadRequestResponse({ ... })
@Validate({
    response: MyResponseSchema,
})
```

But it's still not ideal, because i have some type mismatches between Typebox schema and Nestjs/Swagger decorator requirements. `@ApiOkResponse` for some reasons doesn't like my model `id: Type.Integer({ additionalProperties: false })` type for some reasons (in case you have some ideas on how to fix it as temp workaround):
![image](https://github.com/user-attachments/assets/2497bee5-3c37-4734-8bcc-dc9774801673)

**Comment by jayalfredprufrock** [comment]
Hi there, it's true that this library doesn't attempt to replace _every_  openapi decorator, and only includes support for the metadata that can be extracted from the request/response schemas themselves. That said, I'm surprised to hear that combining this library's decorators with other openapi decorators is not working properly. If you can provide example decorator usage where the openapi and nestjs-typebox decorators work correctly by themselves but not when used together, I'll definitely take a look and see if I can resolve the issue.

I might consider some kind of support for ApiOkResponse(), though again I'd want to be able to extract it from the schema. The idea would be that "description" and "example" would be extracted from the top-level `Type.Object()` (or `Type.Union()` etc.) schema. Is that the behavior you expected? 

I have also considered adding support for error response schema validation, in which case supporting description/example metadata would definitely be in scope as well and work similarly to the above.

**Comment by anotheri** [comment]
@jayalfredprufrock thanks for quick response!

> That said, I'm surprised to hear that combining this library's decorators with other openapi decorators is not working properly. 

Probably my message wasn't clear enough, I don't think the problem i've mentioned is in this library itself. I dig into `@nestjs/swagger` repo issues, and it seems the reason is actually there: https://github.com/nestjs/swagger/issues/1162#issuecomment-2474746736, it seems it's missing the support for latest Open API JSON schema unfortunately. So I can't pass the valid JSON schema into `@ApiOkResponse({ schema: MyTypeboxJsonSchema })`, without getting those TS errors.

> I might consider some kind of support for ApiOkResponse(), though again I'd want to be able to extract it from the schema. The idea would be that "description" and "example" would be extracted from the top-level Type.Object() (or Type.Union() etc.) schema. Is that the behavior you expected?

yes, fwiw I'd expect to have API like this (so kind of superset on top of `@ApiOkResponse` params):
```typescript
@Validate({
    response: {
      schema: MyTypeboxJsonSchema, // Typebox/JSON schema
      stripUnknownProps: true, // optionally
      description: 'Some OK response description', // string
      example: MyOkExampleJson // json which satisfies MyTypeboxJsonSchema
    },
})
```

Thank you in advance!

**Comment by jayalfredprufrock** [comment]
Got it, thanks for the clarification.

Unfortunately, this library is currently bound to the nestjs/swagger implementation and will be subject to any of its shortcomings and bugs. I would love to one day drop that dependency and bring in a more generic openapi generator solution that this library could just feed JSON schemas to, but that might be a long way off.

Regarding your expected api suggestion, I see now what you are after, however I'd much prefer for the schema itself to own the description and example instead of introducing new decorator properties. The schema is supposed to represent the shape of the response so it seems fitting that it should own the description and example. 

```
export const PetSchema = Type.Object({
    id: Type.Number(),
    name: Type.String({
        description: "The pet's name",
        examples: ['Figaro'],
    }),
}, {
   description: 'An object representing a pet.',
   example:  { id: 99, name: 'Figaro' }
});


@Validate({
  response: {
    schema: PetSchema, // description and example are pulled off schema
  },
})

```

I'll close off for now, but feel free to reopen to continue the discussion or report any other findings. Cheers!

**Comment by jayalfredprufrock** [comment]
@anotheri on second thought, the above already sort of works, though the description/example don't get attached to the response itself, but to the content of the response. So perhaps what I'm proposing may not always be intended behavior. I think adding description/example properties to the decorator might actually make sense. I'll see if I can slip this in next time I'm working in the library.

**Comment by anotheri** [comment]
@jayalfredprufrock Yes, exactly!

Although `example` fits more or less good as attachment to schema (as you suggested above), the `description` doesn't fit that well because it's not a description of the schema (e.g. "my object"), but it's description of an OpenAPI enpoint (e.g. "retuns my particular object by id", or "updates my object with these fieds, does something else and returns updated object").

Looking forward into library updates then! 👍

**Comment by jayalfredprufrock** [comment]
@anotheri just a heads up that I published a small release that adds description/example support to response validators. Let me know if you run into any issues.
