### ISSUE TITLE
How to handle Date types?

### ISSUE THREAD

**Issue by anotheri** [jayalfredprufrock/nestjs-typebox#66]
The Typebox allows to define Date type in a couple of ways :

``` typescript
date: Type.String({ format: "date-time" }), // json schema compatible

// or

date: Type.Date({}), // json schema incompatible
```

I'd prefer to go with JSON schema compatible way (see first definition). But I have the problem with this definition using `@Validate` decorator to seriallize result returned from controller. The data I get from service/db uses raw javascript Date and therefore there is type conflict between the types if i return result with js date (e.g. `{ date: new Date() }`.

What is the best way to avoid this kind of type conflicts between? In zod it was possible to address via `z.coerce.date()`, so wondering if there is something like this in `Typebox` or `Nestjs-typebox`.

Thanks in advance!

**Comment by anotheri** [comment]
@jayalfredprufrock yeah I was wondering if that's the way i should use, then i'll probably have to use `date: Type.Date({})` definition (as the most of my code uses raw JS Dates), and wherever it's required, i should do something like:
```
Type.Transform(MySchema).Decode((value) => ({
  ...value,
  myDate: `${value.myDate}`,
}))
```

Is it necessary to define both decode and encode methods?

**Comment by jayalfredprufrock** [comment]
Hi again! Encode is definitely optional but I think things work best if you define both. Your example _should_ work, but I think the more canonical approach would be to define your own custom date type and use that:

```ts
// this assumes format date-time has been registered
const IsoDate = (options) => Type.Transform(Type.String({ format: 'date-time', ...options }))
  .Decode(value => new Date(value))
  .Encode(value => value.toISOString())

// Some schema consuming the type helper
MySchema = Type.Object({
    createdAt: IsoDate()
});
```

Now here's the thing - I think this library needs to adjust the encode/decode semantics. I sort of threw in support without thinking through it fully. The way it should work is that for request schemas, this library should call `Decode()` and the type should be inferred as `StaticDecode<typeof T>`. For response schemas, it should be the exact opposite. This library should call `Encode()` and the return type should be inferred as `StaticEncode<typeof T>`. This will ensure that you can work with a Date() object within your code, but successfully transform to/from it for responses/requests. Note that `Static<typeof T>` is equivalent to `StaticEncode<typeof T>` which means that within your code base you will need to be sure to always use the `StaticDecode<typeof T>` helper to make sure your code aligns with what this library hands you in requests. 

This change should be relatively easy to make and I'm keen to get it in place, but the change is definitely breaking and will require a major version bump. It's likely I'll knock this out over the weekend or early next week. Let me know if you have thoughts regarding any of this.

**Comment by anotheri** [comment]
@jayalfredprufrock Yeah, it sounds good and reasonable to me, thanks! 

Btw, i'm a bit new to Typebox, are the string formats (e.g. `format: 'date-time'`) should be _manually registered_ or Typebox uses them _out of the box_?

**Comment by jayalfredprufrock** [comment]
@anotheri  all string format types require registration for typebox. My library does automatically register email, and I'll probably add some other reasonable format implementations as well. I'll just yoink the super common ones out of typebox's reference implementations here: https://github.com/sinclairzx81/typebox/tree/master/example/formats

But to unblock yourself you can manually register them using the code examples above.

**Comment by jayalfredprufrock** [comment]
@anotheri I have released a new prerelease version that addresses what I mentioned above. (4.0.0-next.1)

Namely, it performs response transformation before validating, request transformation after validating, and uses TransformDecode as the inferred schema type everywhere (except the example, which expects a true Static<T> type, i.e. what the client will be providing). This should allow you to work with decoded types like Date within your codebase while handling serialization in both directions properly.

I also exported the IsoDate type for convenience, and also added several new string formats based on the typebox examples (url, date, time, date-time, uuid, email). 

Besides the breaking behavior of how transform types work and are inferred, I also bumped up the typebox peer dep version to the latest, 0.34.0. It had some breaking changes that affected this library, hence I had to drop support for older typebox versions. I'll probably keep things on a prerelease next branch for a little while until typebox has worked out any kinks on 0.34.x. If things appear stable by the beginning of the year I'll officially release v4.

**Comment by anotheri** [comment]
@jayalfredprufrock awesome, thank you a lot! 🙌

**Comment by anotheri** [comment]
@jayalfredprufrock it works great in the Nestjs application itself, but for some reasons in e2e test (fwiw, i use Vitest environment, with isolated DB, and `@nestjs/testing` module which initiates the whole application module, so i expect the same behaviour), it fails response validation with `message: "Unknown format 'date-time'",`, although controller returns the same data format for both test and main application like this, with dates returned

```typescript
[
  {
    id: 1,
    createdAt: 2024-11-18T23:19:19.291Z, // Date, not string
    updatedAt: 2024-11-18T23:19:19.291Z, // Date, not string
    title: 'hoge',
    content: 'hello world!!',
    published: false,
    accountId: 1
  }
]
```

Test response looks like this:

```typescript
{
  statusCode: 400,
  message: 'Validation failed (response)',
  errors: [
    {
      type: 49,
      schema: [Object],
      path: '/0/createdAt',
      value: '2024-11-18T23:19:19.291Z',
      message: "Unknown format 'date-time'",
      errors: []
    },
    {
      type: 49,
      schema: [Object],
      path: '/0/updatedAt',
      value: '2024-11-18T23:19:19.291Z',
      message: "Unknown format 'date-time'",
      errors: []
    }
  ]
}
```

Any ideas what may cause this behaviour? or how can i debug it?

**Comment by smiley-uriux** [comment]
I'm guessing the bootstrapping code in main.ts isn't being run when executing things in your test harness. Try adding the following code in your testing setup:

```
configureNestJsTypebox({
    setFormats: true,
});
```

**Comment by anotheri** [comment]
@smiley-uriux yeah, thanks, that was it! completely forgot about that configuration.

**Comment by anotheri** [comment]
@jayalfredprufrock @smiley-uriux

Btw, is there a way to import and reuse the same `typebox` instance which is used in `nestjs-typebox`? So in case i need to do some decoding/encoding in my codebase (not as a part of `@Validate` interceptors), i don't need to re-configure those formats in every file where i use `typebox`? Any suggestion here?

I see only `setFormats` and individual exports for each format. Should I import those individual formats and register with typebox instance I use? Because as far as i tried to reuse `setFormats` it doesn't allied to instance i import locally (e.g. in isolated unit-test for service, where the `nestjs-typebox` is not used at all).
